# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

ruby '2.6.6'

gem 'meilisearch', '~>0.18.2'

group :test, :development do
  gem 'byebug'
end
