# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

ruby '3.3.5'

gem 'meilisearch', '~> 0.28.3'

group :test, :development do
  gem 'debug', platforms: %i[mri mingw x64_mingw]
end